apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
  labels:
    app: ai-server
spec:
  selector:
    app: ai-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP