apiVersion: v1
kind: Service
metadata:
  name: backend-server-service
  labels:
    app: backend-server
spec:
  selector:
    app: backend-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP