apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-app
  template:
    metadata:
      labels:
        app: ai-app
    spec:
      containers:
      - name: ai-container
        image: ECR_AI_REPO_URL:latest  # 실제 AI ECR URL로 변경 필요
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  type: ClusterIP
  selector:
    app: ai-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000